name: roboclip
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - mpi=1.0=openmpi
  - mpi4py=3.0.3
  - openmpi
  - setuptools=65.5.0
  - ncurses=6.3=h27087fc_1
  - openmpi=4.1.5=h9a2ec32_100
  - openssl=3.0.8=h0b41bf4_0
  - pip=21.0.1
  - python=3.8.16=he550d4f_1_cpython
  - readline=8.1.2=h0f457ee_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.38.4
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
  - pip:
      - absl-py==0.15.0
      - alembic==1.10.3
      - antlr4-python3-runtime==4.8
      - astunparse==1.6.3
      - bitarray==2.7.3
      - cached-property==1.5.2
      - cachetools==5.2.0
      - certifi==2022.6.15.1
      - cffi==1.15.1
      - chai-sacred==0.8.3
      - chardet==5.1.0
      - charset-normalizer==2.1.1
      - click==8.0.1
      - cloudpickle==2.2.1
      - cmaes==0.9.1
      - colorama==0.4.6
      - colorlog==6.7.0
      - cycler==0.11.0
      - cython==0.29.32
      - dataproperty==0.55.0
      - decorator==4.4.2
      - dm-control==1.0.5
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - fairseq==0.12.2
      - fasteners==0.17.3
      - filelock==3.10.0
      - flatbuffers==1.12
      - fonttools==4.37.1
      - future==0.18.2
      - gast==0.4.0
      - gif2numpy==1.3
      - gitdb==4.0.9
      - gitpython==3.1.27
      - glfw==2.5.5
      - google-auth==2.11.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - greenlet==2.0.2
      - grpcio==1.34.1
      - gym==0.21
      - h5py==3.1.0
      - huggingface-hub==0.13.3
      - huggingface-sb3==2.2.4
      - hydra-core==1.0.7
      - idna==3.3
      - imageio==2.21.2
      - imageio-ffmpeg==0.4.7
      - imitation==0.3.2
      - importlib-metadata==4.13.0
      - joblib==1.1.0
      - jsonpickle==3.0.1
      - kaitaistruct==0.10
      - keras-nightly==2.5.0.dev2021032900
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.4
      - labmaze==1.0.6
      - loguru==0.6.0
      - lxml==4.9.2
      - mako==1.2.4
      - markdown==3.4.1
      - markupsafe==2.1.1
      - matplotlib==3.5.3
      - mbstrdecoder==1.1.2
      - memory-profiler==0.61.0
      - git+https://github.com/aravindr93/mjrl
      - moviepy==1.0.3
        #- mpi4py==3.0.3
      - mujoco==2.2.1
      - mujoco-py==2.1.2.14
      - munch==2.5.0
      - numpy==1.23.4
      - numpy-quaternion==2022.4.2
      - oauthlib==3.2.1
      - omegaconf==2.0.6
      - opencv-python==4.7.0.72
      - opt-einsum==3.3.0
      - optuna==3.1.1
      - packaging==21.3
      - pandas==1.4.4
      - patchelf==0.15.0.0
      - pathtools==0.1.2
      - pathvalidate==2.5.2
      - pillow==9.2.0
      - portalocker==2.7.0
      - proglog==0.1.10
      - promise==2.3
      - protobuf==3.20.1
      - psutil==5.9.2
      - py-cpuinfo==9.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pybullet==3.2.5
      - pycparser==2.21
      - pygame==2.2.0
      - pyglet==1.5.27
      - pyopengl==3.1.6
      - pyparsing==2.4.7
      - pytablewriter==0.64.2
      - python-dateutil==2.8.2
      - pytz==2022.2.1
      - pyyaml==6.0
      - regex==2022.10.31
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rl-zoo3==1.8.0
      - rsa==4.9
      - sacrebleu==2.3.1
      - sb3-contrib==1.8.0
      - scikit-learn==1.1.2
      - scipy==1.9.1
      - seaborn==0.12.2
      - seals==0.1.5
      - sentry-sdk==1.9.8
      - setproctitle==1.3.2
      - shortuuid==1.0.9
      - six==1.15.0
      - smmap==5.0.0
      - sqlalchemy==2.0.9
      - stable-baselines3==1.8.0
      - tabledata==1.3.1
      - tabulate==0.9.0
      - tcolorpy==0.1.2
      - tensorboard==2.11.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6
        #- tensorflow==2.5.0
        #- tensorflow-estimator==2.5.0
      - termcolor==1.1.0
      - threadpoolctl==3.1.0
      - tokenizers==0.13.2
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - tqdm==4.64.1
      - transformers==4.27.2
      - typepy==1.3.0
        #- typing-extensions==4.5.0
      - urllib3==1.26.12
      - wandb==0.13.3
      - wasabi==1.1.1
      - werkzeug==2.2.2
      - wrapt==1.12.1
      - zipp==3.8.1
